---

- name: Check yum mirror list
  shell: yum install -y vi
  register: yum_worked
  ignore_errors: yes

- name: Fix yum mirror list
  shell: |
    cd /etc/yum.repos.d/
    sed -i 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-*
    sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-*
  when: yum_worked.rc != 0

- name: Copy packages to the host
  copy:
    src: "packages/centos{{ ansible_distribution_major_version }}/packages"
    dest: "/tmp/"
    owner: root
    group: root

    directory_mode: 0755



- name: Install packages
  shell: |
    yum --disablerepo=*   install /tmp/packages/*.rpm -y --skip-broken
    yum --disablerepo=*   upgrade /tmp/packages/*.rpm -y --skip-broken


  register: yum_install_packages
  failed_when:
    - ("nothing provides" in yum_install_packages.stderr)

- name: Check if python3.8 is installed

  shell: "python3.8 --version"
  register: python3_check
  ignore_errors: yes

- name: Python installation
  vars:
    python_version_default: 3.8.2
  include_role:
    name: ansible-python37-centos7

  when: python3_check.rc != 0

- name: Upgrade pip3
  shell: "python3.8 -m pip install --upgrade pip"
  ignore_errors: yes



- name: Install pyvenv
  shell: "python3.8 -m pip install   virtualenv --no-index --find-links /tmp/packages/pip"

- name: Install dataclasses
  shell: "python3.8 -m pip install dataclasses --no-index --find-links /tmp/packages/pip"





